#!/usr/bin/env bash
# Update the package list and install nginx
server_name=$(hostname)
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Holberton School - $server_name" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page - $server_name" > /usr/share/nginx/html/custom_404.html
cat <<EOF | sudo tee /etc/nginx/sites-enabled/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        # First attempt to serve request as file, then
        # as a directory, then fall back to displaying a 404.
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;
    }

    add_header X-Served-By $server_name;
	
}
EOF

sudo systemctl restart nginx
