#!/bin/bash
# Update the package list and install nginx
ip1="54.237.61.71"
ip2="54.146.64.127"
server_name=$(hostname)
case $server_name in
    229357-web-01)
        server_ip="$ip1"
        ;;
    229357-web-02)
        server_ip="$ip2"
        ;;
    *)
        server_ip="_"
        ;;
esac
sudo apt update
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Holberton School - $server_name" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page - $server_name" | sudo tee /usr/share/nginx/html/custom_404.html
cat <<EOF | sudo tee /etc/nginx/sites-available/web
server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name $server_ip;

    location / {
        # First attempt to serve request as file, then
        # as a directory, then fall back to displaying a 404.
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;
    }

    add_header X-Served-By $server_name;
	
}
EOF

sudo ln -s /etc/nginx/sites-available/web /etc/nginx/sites-enabled/
if sudo nginx -t;then
    sudo systemctl restart nginx
else
    echo "Nginx configuration test failed. Please check your configuration."
fi
