#!/usr/bin/env bash

# Update the package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server server1 54.237.61.71:80 check
    server server2 54.146.64.127:80 check
EOL

# Enable HAProxy to start at boot
sudo systemctl enable haproxy

# Start HAProxy
sudo systemctl start haproxy

# Verify the HAProxy status
sudo systemctl status haproxy
