#!/usr/bin/env bash
# Docs
config="
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name localhost;

	location / {
		try_files \$uri \$uri/ =404;
	}

}
"
echo "$config" > /etc/nginx/sites-enabled/default
service nginx restart
