#!/usr/bin/env bash
# Comment


start_f()
{

  echo $$ > /var/run/my_process.pid
  echo "manage_my_process started"
  ./manage_my_process &
}

stop_f()
{
  rm -rf /var/run/my_process.pid
  echo "manage_my_process stopped"
  pkill -f manage_my_process
}

restart_f()
{
	high_2
	high_1
}

error_f()
{
	echo "Usage: manage_my_process {start|stop|restart}"
	exit 1
}

if [ $# -ne 2 ]; then
	error_f
fi

case $2 in

	"start")
		start_f
		;;

	"stop")
		stop_f
		;;

	"restart")
		restart_f
		;;
	*)
		error_f
		;;
esac
